export const FETCH_ALL_EXERCISES='FETCH_ALL_EXERCISES';
export const DELETE_EXERCISE='DELETE_EXERCISE';
export const GET_CATEGORIES='GET_CATEGORIES';
export const FETCH_SOLUTION_GROUPS='FETCH_SOLUTION_GROUPS';