export const FETCH_ALL_EXERCISES='FETCH_ALL_EXERCISES';
export const FETCH_ONE_EXERCISE='FETCH_ONE_EXERCISE';
export const DELETE_EXERCISE='DELETE_EXERCISE';
export const GET_CATEGORIES='GET_CATEGORIES';
export const FETCH_SOLUTION_GROUPS='FETCH_SOLUTION_GROUPS';
export const SET_SELECTED_CATEGORY='SET_SELECTED_CATEGORY';